// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/hmmm42/city-picks/internal/adapter/cache"
	"github.com/hmmm42/city-picks/internal/adapter/persistent"
	"github.com/hmmm42/city-picks/internal/config"
	"github.com/hmmm42/city-picks/internal/handler/user"
	"github.com/hmmm42/city-picks/internal/repository"
	"github.com/hmmm42/city-picks/internal/router"
	"github.com/hmmm42/city-picks/internal/service"
	"github.com/hmmm42/city-picks/pkg/logger"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	options, err := config.NewOptions()
	if err != nil {
		return nil, err
	}
	mySQLSetting := options.MySQL
	db, err := persistent.NewMySQL(mySQLSetting)
	if err != nil {
		return nil, err
	}
	userRepo := repository.NewUserRepo(db)
	redisSetting := options.Redis
	client, err := cache.NewRedisClient(redisSetting)
	if err != nil {
		return nil, err
	}
	logSettings := options.Log
	slogLogger, err := logger.NewLogger(logSettings)
	if err != nil {
		return nil, err
	}
	userService := service.NewUserService(userRepo, client, slogLogger)
	loginHandler := user.NewLoginHandler(userService)
	engine := router.NewRouter(loginHandler)
	app := &App{
		Engine: engine,
		Config: options,
	}
	return app, nil
}

// wire.go:

type App struct {
	Engine *gin.Engine
	Config *config.Options
}

var configSet = wire.NewSet(config.NewOptions, wire.FieldsOf(new(*config.Options),

	"MySQL", "Redis", "Log", "JWT", "Server"))

var dbSet = wire.NewSet(persistent.NewMySQL, cache.NewRedisClient)

var loggerSet = wire.NewSet(logger.NewLogger)

var repositorySet = wire.NewSet(repository.NewUserRepo)

var serviceSet = wire.NewSet(service.NewUserService)

var handlerSet = wire.NewSet(user.NewLoginHandler)

var routerSet = wire.NewSet(router.NewRouter)
